/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gologolo;

/**
 *
 * @author yiwang
 */
public enum GoLogoPropertyType {
    
    GL_NAVIGATION_TOOLBAR,
    FONT_OPTIONS,
    FONTSIZE_OPTIONS,
    DEFAULT_FONT,
    DEFAULT_FONTSIZE,
    COLOR_OPTIONS,
    DEFAULT_COLOR,
    DEFAULT_STOP0,
    DEFAULT_STOP1,
    STOP0_OPTIONS,
    STOP1_OPTIONS,
    
    
    GL_PANE,
    GL_LAYERS_PANE,
    GL_LAYES_ITEMSTABLE,
    GL_LAYES_BUTTONS_PANE,
    GL_LAYERS_MOVEUP_BUTTON,
    GL_LAYERS_MOVEDOWN_BUTTON,
    GL_LAYERS_EDIT_BUTTON,
    GL_DRAW_PANE,
    GL_TOOL_PANE,
    
    GL_EXPORT_TEMPLATE_FILE_NAME,
    GL_ORDER_COLUMN,
    GL_NAME_COLUMN,
    GL_TYPE_COLUMN,
    GL_TEST_COLUMN,
    
    GL_COMPONENT_TOOLBAR,
    GL_FONT_TOOLBAR,
    GL_BORDER_TOOLBAR,
    GL_GRADIENT_TOOLBAR,
    
    GL_HOME_BUTTON,
    GL_ENLARGE_BUTTON,
    GL_SHRINK_BUTTON,
    GL_RESIZE_BUTTON,
    GL_SNAP_BUTTON,
    GL_SNAP_LABEL,
    
    
    GL_ADDTEXT_BUTTON,
    GL_ADDIMAGE_BUTTON,
    GL_ADDREC_BUTTON,
    GL_ADDCIR_BUTTON,
    GL_ADDTRI_BUTTON,
    GL_DELETE_BUTTON,
    
    GL_FONTBOX1_TOOLBAR,
    GL_FONTBOX2_TOOLBAR,
    GL_CHOOSEFONT_BOX,
    GL_FONTSIZE_BOX,
    
    GL_B_BUTTON,
    GL_I_BUTTON,
    GL_Tt_BUTTON,
    GL_tT_BUTTON,
    GL_A_BUTTON,
    
    GL_BORDERTHICK_LABEL,
    GL_BORDERTHICK_SLIDER,
    GL_BORDERCOLOR_LABEL,
    GL_BORDERCOLOR_BOX,
    
    GL_BORDERRADIUS_LABEL,
    GL_BORDERRADIUS_SLIDER,
    
    GL_COLORGRADIENT_LABEL,
    GL_FOCUSANGLE_LABEL,
    GL_FOCUSANGLE_SLIDER,
    GL_FOCUSDIS_LABEL,
    GL_FOCUSDIS_SLIDER,
    GL_CENTERX_LABEL,
    GL_CENTERX_SLIDER,
    GL_CENTERY_LABEL,
    GL_CENTERY_SLIDER,
    GL_RADIUS_LABEL,
    GL_RADIUS_SLIDER,
    GL_CYCLEMETHOD_LABEL,
    GL_CYCLEMETHOD_BOX,
    GL_STOP0_LABEL,
    GL_STOP0_BOX,
    GL_STOP1_LABEL,
    GL_STOP1_BOX,
    
    GL_DIALOG_HEADER,
    GL_DIALOG_EDIT_HEADER,
    GL_DIALOG_HEIGHT_PROMPT,
    GL_DIALOG_WEIGHT_PROMPT,
    GL_DIALOG_OK_BUTTON,
    GL_DIALOG_CANCEL_BUTTON,
    GL_DIALOG_EDIT_OK_BUTTON,
    GL_DIALOG_EDIT_CANCEL_BUTTON,
    GL_DIALOG_EDITTEXT_PROMPT,
    
    
    GL_DIALOG_HEADER_TEXT,
    GL_DIALOG_EDIT_HEADER_TEXT,
    GL_DIALOG_HEIGHT_PROMPT_TEXT,
    GL_DIALOG_WEIGHT_PROMPT_TEXT,
    GL_DIALOG_EDITTEXT_PROMPT_TEXT,
    
    GL_DIALOG_NAME_HEADER,
    GL_DIALOG_NAME_HEADER_TEXT,
    GL_DIALOG_NAME_PROMPT,
    GL_DIALOG_NAME_PROMPT_TEXT,
    GL_DIALOG_NAME_OK_BUTTON,
    GL_DIALOG_NAME_CANCEL_BUTTON,

    GL_FOOLPROOF_SETTINGS,
    GL_ITEM_DIALOG_FOOLPROOF_SETTINGS;
    
    
}
